zetaxbot:  
  right_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      # SHR
      - J1
      # BICR
      - J2
      # BICEP
      - J3
      # HAND
      - J4
      # WRISTER
      - J5
  # Arm TraJectory Controllers ---------------------------------------
  left_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      # SHL
      - J24
      # BICL
      - J25
      # BICEPL
      - J26
      # HANDL
      - J27
      # WRISTL
      - J28
  head_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      # head
      - J46
      - J47

