controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - J24
      - J25
      - J26
      - J27
      - J28
  - name: fake_head_controller
    type: $(arg fake_execution_type)
    joints:
      - J46
      - J47
  - name: fake_right_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - J10
      - J13
      - J16
      - J20
      - J7
initial:  # Define initial robot poses per group
  - group: right_arm
    pose: init_right_arm